#!/bin/bash
# AUTO-GENERATED BY ./tools/findings_script_gen.py

if [ $# -lt 1 ]; then
    echo >&2 "usage: $0 <fuzzer> [mode]"
    exit 1
fi

ARG=$1
shift
case $ARG in
afl|afl_asan|afl_resume|aflfast|angora|ddfuzz|eclipser|fairfuzz|instrim|k_scheduler|moptafl|moptafl_asan|parmesan|symcc_analysis)
    MODE=${1:-0}
    CRASH_DIR="$SHARED/findings/crashes"
    QUEUE_DIR="$SHARED/findings/queue"
    HANGS_DIR="$SHARED/findings/hangs"
    if [ ! -d "$CRASH_DIR" ]; then
        exit 1
    fi
    find "$CRASH_DIR" -type f -name 'id:*'
    if [ "$MODE" = 0 ]; then
        exit
    elif [ ! -d "$QUEUE_DIR" ] || [ ! -d "$HANGS_DIR" ]; then
        exit 1
    fi
    find "$QUEUE_DIR" -maxdepth 1 -type f -name 'id:*'
    find "$HANGS_DIR" -type f -name 'id:*'
    ;;
aflplusplus|aflplusplus_lto|aflplusplus_lto_asan)
    MODE=${1:-0}
    CRASH_DIR="$SHARED/findings/default/crashes"
    QUEUE_DIR="$SHARED/findings/default/queue"
    HANGS_DIR="$SHARED/findings/default/hangs"
    if [ ! -d "$CRASH_DIR" ]; then
        exit 1
    fi
    find "$CRASH_DIR" -type f -name 'id:*'
    if [ "$MODE" = 0 ]; then
        exit
    elif [ ! -d "$QUEUE_DIR" ] || [ ! -d "$HANGS_DIR" ]; then
        exit 1
    fi
    find "$QUEUE_DIR" -maxdepth 1 -type f -name 'id:*'
    find "$HANGS_DIR" -type f -name 'id:*'
    ;;
entropic|libfuzzer)
    CRASH_DIR="$SHARED/findings"
    if [ ! -d "$CRASH_DIR" ]; then
        exit 1
    fi
    find "$CRASH_DIR" -type f
    ;;
honggfuzz|honggfuzz_asan)
    MODE=${1:-0}
    CRASH_DIR="$SHARED/findings"
    QUEUE_DIR="$SHARED/output"
    if [ ! -d "$CRASH_DIR" ]; then
        exit 1
    fi
    find "$CRASH_DIR" -type f -name '*.fuzz'
    if [ "$MODE" = 0 ]; then
        exit
    elif [ ! -d "$QUEUE_DIR" ]; then
        exit 1
    fi
    find "$QUEUE_DIR" -type f -name '*.cov'
    ;;
symcc_afl)
    CRASH_DIRS=("$SHARED/findings/afl-master/crashes" "$SHARED/findings/symcc/crashes")
    if [ ! -d "${CRASH_DIRS[0]}" ] && [ ! -d "${CRASH_DIRS[1]}" ]; then
        exit 1
    fi
    find ${CRASH_DIRS[@]} -type f -name 'id:*'
    ;;
aflgo_new)
    MODE=${1:-0}
    CRASH_DIR="$SHARED/findings/crashes"
    QUEUE_DIR="$SHARED/findings/queue"
    if [ ! -d "$CRASH_DIR" ]; then
        exit 1
    fi
    find "$CRASH_DIR" -type f
    if [ "$MODE" = 0 ]; then
        exit
    elif [ ! -d "$QUEUE_DIR" ]; then
        exit 1
    fi
    find "$QUEUE_DIR" -maxdepth 1 -type f \! -name '.*'
    ;;
*)
    echo >&2 "fuzzer $ARG is not recognized"
    exit 1
    ;;
esac
