#!/bin/bash
# AUTO-GENERATED BY ./tools/runonce_script_gen.py

if [ $# -lt 2 ]; then
    echo >&2 "usage: $0 <fuzzer> <testcase>"
    exit 1
fi

ARG=$1
shift
case $ARG in
afl|afl_asan|afl_resume|aflfast|entropic|fairfuzz|honggfuzz|honggfuzz_asan|instrim|k_scheduler|libfuzzer|llvm_analysis|llvm_cov|moptafl|moptafl_asan|vanilla)
    CMD="run_limited '$OUT/$PROGRAM' $args"
    ;;
aflplusplus|aflplusplus_lto|aflplusplus_lto_asan|ddfuzz|symcc_afl|symcc_analysis)
    CMD="run_limited '$OUT/afl/$PROGRAM' $args"
    ;;
angora|parmesan)
    CMD="run_limited '$OUT/angora-fast/$PROGRAM' $args"
    ;;
eclipser)
    CMD="run_limited '$OUT/eclipser/$PROGRAM' $args"
    ;;
*)
    echo >&2 "fuzzer $ARG is not recognized"
    exit 1
    ;;
esac

export TIMELIMIT=1s
export MEMLIMIT_MB=200

run_limited()
{
    set -e
    ulimit -Sv $[MEMLIMIT_MB << 10];
    ${@:1}
}
export -f run_limited

args="${ARGS/@@/"'$1'"}"
if [ -z "$args" ]; then
    args="'$1'"
fi

timeout --kill-after 3s --preserve-status $TIMELIMIT bash -c "$CMD"
